# config/_default/languages.en.toml

title = "home"

[params.author]
name = "Giuachin Kreiliger"
image = "img/author.jpg"
avatar = "/img/author.jpg"
headline = "Doktorand an der Universität Zürich"
bio = "Wissenschaft, Statistik und Medien"
links = [
  { bluesky = "https://bsky.app/profile/giuachin.bsky.social" }
]

